---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/1/sleep_records/1":
    get:
      summary: Detail
      tags:
      - Sleep Records
      responses:
        '200':
          description: Record found
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleep_record:
                    id:
                      type: integer
                    sleep_time:
                      type: string
                      format: date-time
                    wake_up_time: '2025-07-02T20:28:47Z'
                    duration_hours: 7.0
                    duration_seconds: 25200
                    created_at: '2025-08-13T14:28:03Z'
                    user:
                      id: 1
                      name: Jona Davis I
                      created_at: '2025-08-13T14:27:38Z'
                required:
                - id
                - title
                - content
        '404':
          description: Record not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
